### ISSUE TITLE
Any way to use with corrected PacBio reads?

### ISSUE THREAD

**Issue by driscolc** [lmrodriguezr/nonpareil#13]
I know that curve generation is optimized for small reads as stated on your website, but is there a way to use this program on corrected PacBio reads?

**Comment by lmrodriguezr** [comment]
Hello @driscolc.
Thanks for your interest in Nonpareil! Unfortunately, we're not planning on extending support to PacBio. I've now included a detailed response for this in [Nonpareil's FAQ](http://enve-omics.ce.gatech.edu/nonpareil/faq#pacbio).

However, I would be curious to know about the target community (sample), perhaps I can offer some workaround (?). I'm closing the issue for now.

**Comment by driscolc** [comment]
Hi Luis,

Thanks for the timely response! My sample is from a relatively 
non-diverse, non-axenic bacterial culture obtained from a freshwater 
lake sample. We've sequenced with 8 SMRT cells of PacBio (~2GB file of 
filtered, corrected reads), and have closed three genomes, although we 
have evidence of perhaps up to half a dozen bacterial genomes from 
Illumina sequencing on the same culture. I wanted to assess how much of 
the diversity in the sample we are reaching through PacBio sequencing by 
comparing nonpareil curve results from both PacBio and Illumina reads 
(my goal is to publish this as a PacBio shotgun metagenome of sorts). If 
you have any ideas for a workaround, that would be fantastic. Just so 
you know, I have tried using the base program on the corrected reads 
already, but usually get an aborted core dumped error, even when using 
60 cores.

Thanks,

Connor

**Comment by lmrodriguezr** [comment]
Since you have SMRT cells, I would say that the quality is not much of an issue. However, the length is still a problem, because PacBio lengths would cause a decrease in sensitivity and perhaps even some segmentation faults in the implementation. Since you have a low-diversity sample, one way to solve this is to simulate Illumina-like reads from the PacBio reads, perhaps extracting a 500bp-long piece of each PacBio read (maybe even longer, say 1kb), and then running Nonpareil on the resulting set. Do not extract multiple fragments from the same PacBio read, though, since Nonpareil assumes that each read represents an independent event. It would be a very small set, but perhaps it could be enough, I don't know. If everything goes well, the resulting set would produce an underestimation of the coverage, but you could simply check the coverage of the real sequencing effort in the projected Nonpareil curve at the end to get the actual coverage of your dataset.

Another option I see, especially since it's a low-diversity sample, is to use a marker gene (e.g. 16S, or gyrB, or rpoB), generate OTUs, and apply [preseq](http://smithlabresearch.org/software/preseq/). 16S is not very sensitive at the species boundary, but it could be used if you know the different species you have are not closely related (e.g., they are all from different genera, or even different families). Otherwise, I would recommend using marker genes, perhaps with the identity thresholds recommended in the [mOTU paper](http://www.nature.com/nmeth/journal/v10/n12/full/nmeth.2693.html).

**Comment by jianshu93** [comment]
Hello both,

It has been some time since last discussion. I am wondering the FAQs mentioned here (http://enve-omics.ce.gatech.edu/nonpareil/faq#pacbio) still apply because PacBio now can be almost as accurate as Illumina short reads and also high throughput, e.g, several million PacBio SMRT reads from environmental metagenome samples are very common these days. Evaluating the identities among reads (especially long reads) for higher than 95% identity is now easy/fast due to theoretical breakthroughs in kmer-based LSH algorithms (Marçais et.al., 2019; Jain et.al., 2017).  We do not need to do alignment (gapped or ungapped) any more for long reads to estimate identity but using MinHash or related. Those ideas are more complicated to implement. In the case of alignment (if still needs to be done) for long reads, it seems edit distance (https://github.com/Martinsos/edlib)  (unit score scheme) make no difference to dynamic programming (various score scheme) in the alignment mode for >95% identity threshold. Maybe for long reads we need to lower the identity threshold somehow for reads to be considered redundant (e.g., > 90%). Some report from running nonpareil for human gut PacBio SMRT samples, 2 million reads, 4-kb length on average: it did ran but sampling and counting is never parallelized (I see it was for short reads). If identity calculating step is no problem, I feel the comparing model should also apply for accurate long reads since the underlying premise still holds (Lander-Waterman, or more broadly the generalization of Stevens’ Theorem). Just want to hear comments from both on whether it is worth it to extend to long reads metagenomic samples. 

Thank you,

Jinashu

**Comment by JotaKas** [comment]
Any news and/or parameter recommendations for PacBio HiFi reads?
