### ISSUE TITLE
Nonpareil.curve fails on test dataset

### ISSUE THREAD

**Issue by gisleDK** [lmrodriguezr/nonpareil#18]
nonpareil -s test.fastq -T alignment -b test -f fastq

R version 3.2.5 (2016-04-14)
> library,(Nonpareil);
> Nonpareil.curve('test.npo');
Error in if (a[twenty.pc, 5] == 0) { : argument is of length zero
In addition: Warning message:
In log(read.length) : NaNs produced

**Comment by lmrodriguezr** [comment]
@gisleDK May I see the `test.npo` file?

Thanks!

**Comment by gisleDK** [comment]
Must definitely and thanks for the fast reply!
[test.npo](https://gist.github.com/gisleDK/2090cde28ddab98b1fc8ee9f8469c86f)

**Comment by lmrodriguezr** [comment]
Hello @gisleDK , sorry for the delay answering.
It looks like you're using a short-lived version that had a bug in it. Please update the codebase, re-compile, and re-run the test. The problem is in the run of the binary, not in the R library. Sorry for the inconvenience, I hope this solves the issue.

BTW, the problematic line in the `test.npo` file is:
```
# @ksize: 32644
```

That should be:
```
# @ksize: 0
```
