### ISSUE TITLE
Installation of nonpareil via conda

### ISSUE THREAD

**Issue by bebatut** [lmrodriguezr/nonpareil#24]
Hi,

Nonpareil has been integrated into [Bioconda](http://bioconda.github.io/), to facilitate its installation via conda: http://bioconda.github.io/recipes/nonpareil/README.html (the latest version will be soon available)
If you want, I can open a Pull Request here to update the README file and the doc to add how to install Nonpareil using conda and also the badge: [![install with bioconda](https://img.shields.io/badge/install%20with-bioconda-brightgreen.svg?style=flat-square)](http://bioconda.github.io/recipes/nonpareil/README.html).

Bérénice

**Comment by lmrodriguezr** [comment]
These are great news @bebatut !
Yes, please open a PR to add the badge to README + Docs. Are the new released versions added automatically? The v3.2 (just released) resolved an important bug in the diversity estimates that affected libraries of extreme sizes (very large or very small). This release will likely stay stable for a while because it's the codebase on the next publication (coming up soon).

Thanks!
Miguel.

**Comment by bebatut** [comment]
The new releases are not added automatically. I will update the conda package. 
BTW, we also created a Galaxy wrapper for Nonpareil: https://toolshed.g2.bx.psu.edu/view/iuc/nonpareil/280386b252a5. It can be used on any Galaxy instance. Will you be interested to add this info to the doc too?

**Comment by lmrodriguezr** [comment]
Awesome!

> Will you be interested to add this info to the doc too?

Yes, please :)

**Comment by bebatut** [comment]
I created PR to update the conda package of Nonpareil: https://github.com/bioconda/bioconda-recipes/pull/6784
Once it will be merged, it will automatically add a new version for the conda package and also for the Biocontainer
