### ISSUE TITLE
Bug in arrow placement with R packages?

### ISSUE THREAD

**Issue by bramvandijk88** [lmrodriguezr/nonpareil#55]
Heya,

I am assuming this is a simple bug, but just to be sure I will ask here. The arrows for indicating the sequencing effort seem to be placed wrongly for my data. (see figure below)
![image](https://user-images.githubusercontent.com/11132992/193803014-987ec88d-4667-490e-a862-eae9cfcd1d8e.png)

**Comment by lmrodriguezr** [comment]
Hi @bramvandijk88
Sorry for the long delay, I missed when this issue was opened. This is not an issue with the code, but with the documentation: The arrows are not properly documented, but they actually represent the location corresponding to `exp(Nd)`, which is a metric of _sequence diversity_ based on the projection of the Nonpareil curve. Curves with corresponding arrows that are more to the right indicate a higher sequence diversity. The location of the estimate for the full dataset can be determined in your curves by the right-most point of the solid lines. Alternatively, if you choose not to display the rarefied curve (model only) Nonpareil will indicate the corresponding point with a little disc (and empty circle).

I'll leave this issue open until we expand the documentation. Thanks for your report!
Miguel.

**Comment by lmrodriguezr** [comment]
Transferring to #58
