### ISSUE TITLE
No output files

### ISSUE THREAD

**Issue by daisykuma22** [lmrodriguezr/nonpareil#56]
Dear developers,

Thank you for designing this excellent software. I have a question when running nonpareil. It seems everthing goes fine, but there is no output files. My code is 'nonpareil -b ./output-S11-0/ -s ./S11-0_1.fasta -f fasta -t 6 -R 400000 -T alignment'. The log is as below:
Nonpareil v3.401
 [      0.0]  Counting sequences
 [      8.6]   The file ./S11-0_1.fasta.enve-seq.37400 was just created
 [      8.6]     Longest sequence has 150 characters
 [      8.6]     Average read length is 149.336299 bp
 [      8.6]  Reading file with 90305189 sequences
 [      8.6]  Counting query sequences
 [      8.6]    Sequences to store in 399997.955078Mb free: -1553606656 (3035.662369%)
 [      8.6]  Querying library with 0.000011 times the total size (1000 seqs)
 [      8.6]    Building query set at ./S11-0_1.fasta.enve-seq.37400.subsample.37400
 [      8.9]     Query set built with 989 sequences
 [      8.9]      Designing the blocks scheme for 90305189 sequences
 [      8.9]       Qry blocks:1, seqs/block:989
 [      8.9]       Sbj blocks:1, seqs/block:90305189
 [      8.9]    Mating sequences in 1 by 1 blocks
 [      8.9]      Allocating ~0 Mib in RAM for block qry:1
 [      8.9]      Allocating ~12918 Mib in RAM for block sbj:1
 [      9.5]     Computing block 1/1
 [      9.5]      Launching parallel comparisons to 6 threads
 [  17008.4]     Thread 5 completed 164 comparisons, joining results                              
 [  17037.6]     Thread 1 completed 165 comparisons, joining results                              
 [  17046.0]     Thread 4 completed 165 comparisons, joining results                              
 [  17052.9]     Thread 0 completed 165 comparisons, joining results                              
 [  17054.4]     Thread 2 completed 165 comparisons, joining results                              
 [  17057.5]     Thread 3 completed 165 comparisons, joining results                              
 [  17057.7]  Sub-sampling library
 [  17057.7]  Evaluating consistency                                  
 [  17057.7]  Everything seems correct

Thanks for helping this out.
Daisy

**Comment by lmrodriguezr** [comment]
Dear Daisy, thank you for your report.

Please note that the `-b` option serves to specify the base path of the output files, not just the directory. Since your value ends in `/`, the system will simply append the extensions (e.g., `.npl` and `.npo`) to that base path, creating hidden files within that directory. I suspect your files do exist, but they're hidden (because they start with `.`). You can check with `less output-S11-0/.npo` or `ls -A output-S11-0/`.

To solve the issue more generally, you can simply modify the command, for example using `-b output-S11-0/np-out` or something similar.

Please let us know if that solves the issue.

Best wishes,
Miguel.

**Comment by daisykuma22** [comment]
Thank you, Miguel. Yes, all results exist in the form of hidden files. And the problem has been solved by  using the suggested command.
